# Purpose

This project consists of recreating the figures found at
<https://www.fmx.nfkatzke.com/posts/2020-08-05-practical-1/> which
display the cumulative return of the FTSE JSE Allshare Index since
January 2002 and January 2010 under different management fees
structures.

# Fee Impact on Cumulative returns since 2002

![Fee Impact on Cumulative Returns since January
2002](README_files/figure-markdown_github/fig_2002-1.png)

<table>
<caption>
Relative Impact of Fees on Wealth since 2002
</caption>
<thead>
<tr>
<th style="text-align:left;">
bp
</th>
<th style="text-align:left;">
prop
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Return - 10 bps
</td>
<td style="text-align:left;">
-1.8%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 50 bps
</td>
<td style="text-align:left;">
-8.9%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 100 bps
</td>
<td style="text-align:left;">
-17%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 200 bps
</td>
<td style="text-align:left;">
-31.2%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 250 bps
</td>
<td style="text-align:left;">
-37.3%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 350 bps
</td>
<td style="text-align:left;">
-48%
</td>
</tr>
</tbody>
</table>

The above figure illustrates the impact that different fees structures
have on cumulative returns since 2002. The figure shows the impact of a
fee of 10, 50, 100, 200, 250, and 350 bps per annum on the cumulative
returns of the FTSE JSE All Share Index since January 2002. The table
shows the cumulative effect on the proportion lost due to fess over the
time period.

# Fee Impact of Cumulative returns since 2010

![Fee Impact on Cumulative Return since January
2010](README_files/figure-markdown_github/fig_2010-1.png)

<table>
<caption>
Relative Impact of Fees on Wealth since 2010
</caption>
<thead>
<tr>
<th style="text-align:left;">
bp
</th>
<th style="text-align:left;">
prop
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Return - 10 bps
</td>
<td style="text-align:left;">
-1.1%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 50 bps
</td>
<td style="text-align:left;">
-5.4%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 100 bps
</td>
<td style="text-align:left;">
-10.6%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 200 bps
</td>
<td style="text-align:left;">
-20%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 250 bps
</td>
<td style="text-align:left;">
-24.4%
</td>
</tr>
<tr>
<td style="text-align:left;">
Return - 350 bps
</td>
<td style="text-align:left;">
-32.4%
</td>
</tr>
</tbody>
</table>

The above figure similarly illustrates the impact that different fees
structures have on cumulative returns but since 2010. The figure shows
the impact of a fee of 10, 50, 100, 200, 250, and 350 bps per annum on
the cumulative returns of the FTSE JSE All Share Index since January
2010. The table shows the cumulative effect on the proportion lost due
to fess over the time period.
